[Alex] step-2 체스판 생성
codesquad-members-2024/be-chess pull request #78
Opened 2024-03-06 01:35 UTC by horanga

## 구현 내용
-추후에 board에 Pawn 말고 다른 Piece들도 들어올 것을 대비해서 Pawn 클래스를 상위클래스인 Piece를 상속하도록 했고, Board의 메서드들도 인자를 Piece로 받는 방식을 구현함

-Pawn 인스턴스들이 동일한지 확인하기 위해서 hascode와 equals 자동 오버라이드 기능을 활용했음

## 고민 사항
테스트에서 중복된 부분을 before 애노테이션을 사용하라는 요구사항이 있었는데, 현재 상황에서는 board라는 컬렉션에 Pawn인스턴스를 넣는 부분이 중복됐음. 그런데, 이걸 beforeEach를 쓰려면 board라는 컬렉션이 전역적으로 접근할 수 있는 필드변수가 돼야 한다. 이렇게 되면 테스트간에 서로 간섭을 하게 되기 때문에 테스트 구조 측면에서 좋지 않다고 판단을 했음.

-Pawn 말고 다른 데이터 타입이 들어오면 컴파일 에러가 뜨게끔 구성하라고 해서 인자를 상위클래스 타입인 Pices로 설정해둠. 근데 컴파일 에러가 뜨는 걸 테스트하는 방법은 없는 거 같아서 코드는 각주 처리로 작성해두기만 함

## 기타

2024-03-06 03:28 UTC, honux77 commented on untitled/src/main/java/org/example/chess/Board.java
> +package org.example.chess;
패키지 이름에서 org.example은 제거해 주세요.

2024-03-06 03:29 UTC, honux77 commented on untitled/src/main/java/org/example/chess/Board.java
> +    public Piece findPiece(int number){
number 보다는 index나 location 같은 이름이 좋을 것 같습니다.

2024-03-06 03:30 UTC, honux77 requested changes
지금 최상위 폴더가 untitled 도 되어 있는데 하나씩 상위로 옮겨 주세요. 
그리고 기타 코멘트도 확인해 주세요.

2024-03-06 03:30 UTC, honux77 commented on untitled/src/main/java/org/example/piece/Pawn.java
> +    String color;
```suggestion
```

2024-03-06 03:32 UTC, honux77 commented on untitled/src/main/java/org/example/piece/Pawn.java
> +        if(!color.equals(BLACK)&&!color.equals(WHTIE)){
코드 포매팅도 신경써 주세요.

2024-03-06 22:39 UTC, honux77 commented on src/main/java/chess/Board.java
> +    }
continue가 많아서 지저분해 보입니다. 다음에는 이 부분을 깔끔하게 개선해 주세요.

2024-03-06 22:39 UTC, honux77 commented on src/main/java/chess/Board.java
> +    }
1, 6 도 매직 넘버 입니다. 제거해 주세요.

2024-03-06 22:40 UTC, honux77 commented on src/main/java/piece/Pawn.java
> +}
불필요한 코드 같네요. 확인해 보고 불필요하면 제거해 주세요.

2024-03-06 22:42 UTC, honux77 commented on src/main/java/piece/Pieces.java
> +    NONE("NONE", ".");
Piece 라는 enum 타입에 black이라는 다른 정보가 포함되어 있습니다. 클래스의 원래 의미와 맞지 않다고 생각합니다.

2024-03-06 22:43 UTC, honux77 requested changes
전반적으로 요구사항보다 지나치게 많은 내용이 코드에 담겨있어요. 
다음 단계를 고려하지 말고 주어진 단계에서 가장 단순한 코드가 될 수 있도록 재작성해 주세요. 

수정 완료 후에는 코멘트도 하나 추가해 주세요.

2024-03-07 02:07 UTC, horanga commented on src/main/java/piece/Pieces.java
> +    NONE("NONE", ".");
그렇게 한 이유는 

https://techblog.woowahan.com/2527/

여기서 좀 영감을 받아서 이번에 적용해보았습니다. 
![사진1](https://github.com/codesquad-members-2024/be-chess/assets/148988364/7eee8fd7-a48e-4a0f-a34e-68ddc74a833a)

여기 사진을 보면 어떤 변수를 놓고 그 변수를 나타내는 데이터들을 연결해주는 용도로 enum을 사용했는데, 추후에 피스들에 정보들이 계속 늘어날 것같아서 이렇게 적용을 해봤는데 저 사진과는 다른 방식으로 쓰여진걸까요?

2024-03-07 02:10 UTC, honux77 commented on src/main/java/piece/Pieces.java
> +    NONE("NONE", ".");
저 방식은 같은 데이터의 다른 표현이구요. 지금은 검정과 폰은 직접적인 연관이 없죠. 잘못된 응용이라고 생각해요.

2024-03-07 02:11 UTC, horanga commented on src/main/java/piece/Pawn.java
> +}
현재 코드에서 불필요해서 제거했습니다!

2024-03-07 02:17 UTC, horanga commented on src/main/java/piece/Pieces.java
> +    NONE("NONE", ".");
이 내용도 수정하겠습니다!

2024-03-07 05:28 UTC, horanga commented
변경사항 최종 수정했습니다!

color를 enum으로 만들려다 enum도 null체크를 해야 한다고 들어서 그렇다면 그냥 String으로 black과 white만 받게 하고 그렇지 않으면 예외처리를 하는 것도 괜찮을 거 같아서 색은 상수로 정의해두었습니다. 데이터가 검은색과 하얀색 둘뿐이라서 상수로 처리해도 괜찮을 거 같다고 생각했습니다.

2024-03-07 06:33 UTC, honux77 commented on src/main/java/chess/Board.java
> +    private static List<List<Piece>> BOARD = intialize();
```suggestion
    private static List<List<Piece>> board = intialize();
```

상수가 아닌 객체는 대문자로 하지 않습니다.

2024-03-07 06:34 UTC, honux77 commented on src/main/java/chess/Board.java
> +    private static List<List<Piece>> intialize() {
```suggestion
    private static void intialize() {
```

멤버변수가 있는데 리턴할 필요가 없겠죠?

2024-03-07 06:48 UTC, horanga commented on src/main/java/chess/Board.java
> +    private static List<List<Piece>> intialize() {
내용 수정했습니다! intialize를 여러번 사용할 필요가 없도록 멤버변수로 캐싱해두고 get하는 방식을 썼었는데, 메서드 가독성이 좋지 않은거 같아서 멤버변수에 직접 add 해준는 방식을 썼습니다. initialize를 외부에서 계속 쓰게 하는 것도 좋은 선택지가 아닌 거 같아서 static 블록으로 처음에 실행하도록 했습니다.

2024-03-07 10:03 UTC, honux77 commented
고치느라 수고하셨어요! 👍

2024-03-07 10:03 UTC, merged