[이브이] step-3 체스판 초기화
codesquad-members-2024/be-chess pull request #82
Opened 2024-03-06 02:28 UTC by lotuxsoo

## 구현 내용
### Board 클래스 작성
- ArrayList를 5개 만들어서 initialize() → print() 구현
### main 함수 수정
- 사용자에게 입력을 받도록 Scanner 생성
- start, end 입력받게함
### 중복 리팩토링
- 빈칸을 나타내는 부분은 ArrayList -> String으로 변경했다.
- getPieceResult() 함수로 변경해서 파라미터로 color, piece를 받아서 다중 if
문으로 처리하게 했다. 좋은 방법은 아닌거 같다..

## 고민 사항
- 요구사항 대로 따라가고 있는데, 머릿속의 구현 내용이랑 조금 상충돼서 고민됐다.

## 기타

2024-03-06 05:40 UTC, honux77 commented
main에다 올렸어요 ㅋㅋ

2024-03-06 05:55 UTC, honux77 commented
요구사항 대로 따라가고 있는데, 머릿속의 구현 내용이랑 조금 상충돼서 고민됐다.
--> 하고 싶은 내용이 있으면 그 내용을 따라 가도 됩니다.

2024-03-06 05:56 UTC, honux77 commented on src/main/java/chess/Board.java
> +    //Object[][] chessPan;
쓰지 않는 코드 주석은 PR 보내기 전에 삭제해 주는 게 좋습니다.

2024-03-06 05:57 UTC, honux77 commented on src/main/java/chess/Board.java
> +    ArrayList<Object> whitePieces;
제네릭에 Object는 일반적으로 사용하지 않습니다. Object는 사용하지 않도록 수정해 주세요.

2024-03-06 05:58 UTC, honux77 commented on src/main/java/chess/Board.java
> +        for (int i = 0; i < 8; i++) {
8 과 같은 매직 넘버는 제거해 주세요.

2024-03-06 06:00 UTC, honux77 commented on src/main/java/chess/Board.java
> +            blackPieces.add('•');
. 이 아닌 다른 객체를 만들어 추가하는 것이 일관성 있는 코드가 될 거 같아요.

2024-03-06 06:04 UTC, honux77 requested changes
지금 3단계와 4단계의 요구사향이 묘하게 섞여 있는데 코드의 복잡도는 높고 완성도는 낮은 편입니다. 
주어진 요구사항을 만족하는 수준으로 작성하고 복잡하거나 불필요한 코드는 삭제해 주세요.

특히 Piece.java를 제거해 주세요.

2024-03-06 08:10 UTC, lotuxsoo commented
> main에다 올렸어요 ㅋㅋ

죄송합니다😰

2024-03-06 08:20 UTC, lotuxsoo commented
> 지금 3단계와 4단계의 요구사향이 묘하게 섞여 있는데 코드의 복잡도는 높고 완성도는 낮은 편입니다. 주어진 요구사항을 만족하는 수준으로 작성하고 복잡하거나 불필요한 코드는 삭제해 주세요.
> 
> 특히 Piece.java를 제거해 주세요.

수정사항 전부 반영해서 다시 push 했습니다. 리뷰 감사합니다!! 🫡

2024-03-06 22:44 UTC, honux77 commented
@lotuxsoo 2단계 반영 때문에 충돌이 났네요. 충돌 해결해 주세요.

2024-03-07 02:45 UTC, honux77 commented
수정하느라 수고하셨어요. 머지할게요~

2024-03-07 02:45 UTC, merged